replicaCount: 1
service:
  port: 80
  type: "ClusterIP"
greeting: "Testing"
favorite:
  drink: "coffee"
  food: "pizza"
token: "dev-token"
image:
  tag: latest
  repository: "registry.hub.docker.com/library/alpine"
