image:
  tag: ""
  repository: "nginx"
  pullPolicy: "IfNotPresent"
nameOverride: ""
podSecurityContext: {}
replicas: "1"
imagePullSecrets: []
greeting: "Testing"
resources: {}
serviceAccount:
  name: ""
  create: false
  annotations: {}
securityContext: {}
podAnnotations: {}
branch: "develop"
nodeSelector: {}
ingress:
  hosts:
  - paths:
    - path: "/"
      pathType: "ImplementationSpecific"
    host: "chart-example.local"
  annotations: {}
  className: ""
  tls: []
  enabled: false
replicaCount: 1
tolerations: []
service:
  port: 80
  type: "ClusterIP"
fullnameOverride: ""
artifactServer: "nginx_docker"
autoscaling:
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  enabled: false
affinity: {}
