{{- $configmapname := printf "%s-%s" $.Values.name "configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapname }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
  labels:
    app: {{ $.Values.name }}
data:
  myvalue: {{ $.Values.greeting | quote }}
  drink: {{ $.Values.favorite.drink | quote  }}
  food: {{ $.Values.favorite.food | upper | quote }}
