apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configmap
  labels:
    app: myapp
data:
  myvalue: {{ .Values.greeting | quote }}
  drink: {{ .Values.favorite.drink | quote  }}
  food: {{ .Values.favorite.food | upper | quote }}
